module.exports={
  caseType:'approved_renewable_operations_dispatch',initialState:'asset_event_registered',
  states:['asset_event_registered','telemetry_reconciled','constraints_locked','scenario_replayed','dispatch_proposed','operator_review','dispatch_approved','execution_observed','execution_failed','offline_pending','manual_fallback_verified','outcome_reconciled','closed'],
  createRoles:['renewable_planner','operations_manager'],assessmentRoles:['renewable_planner','operations_reviewer','safety_reviewer'],auditRoles:['operations_manager','safety_reviewer','auditor'],connectorRoles:['integration_operator','operations_manager'],
  evidenceKinds:['telemetry_manifest','scada_snapshot','asset_site_snapshot','gis_version','constraint_manifest','weather_snapshot','maintenance_window','historical_replay','forecast_report','optimization_report','operator_approval','dispatch_receipt','execution_feedback','offline_receipt','failure_record','manual_fallback_record','outcome_report'],
  requiredSignals:['telemetryVersion','scadaVersion','assetVersion','gisVersion','constraintVersion','modelVersion','policyVersion','safetyLimitsVerified','sourceFreshnessSeconds','forecastError','constraintViolations','p95LatencyMs','missedEventRate','realizedOutputRatio','offlineStatus'],
  professionalBoundary:'Plans remain proposals for qualified renewable-operations personnel. Assessment cannot command SCADA, inverters, turbines, grid bids, equipment, or field dispatch.',
  connectors:[{name:'telemetry',purpose:'timestamped read-only generation observations'},{name:'scada',purpose:'read-only control-system snapshots and receipts'},{name:'erp_wms_tms',purpose:'work, inventory, and logistics status'},{name:'device',purpose:'read-only turbine, inverter, meter, and sensor status'},{name:'gis',purpose:'versioned asset and site geometry'},{name:'weather',purpose:'forecast and observed-condition receipts'},{name:'maintenance',purpose:'maintenance windows and feedback'},{name:'grid_market',purpose:'ISO, RTO, meter, and curtailment status'},{name:'notification',purpose:'approved operator delivery receipts'}],
  transitions:[
    {from:'asset_event_registered',action:'reconcile_telemetry',to:'telemetry_reconciled',roles:['renewable_planner','integration_operator'],requiresEvidence:true},
    {from:'telemetry_reconciled',action:'lock_constraints',to:'constraints_locked',roles:['operations_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'constraints_locked',action:'record_historical_replay',to:'scenario_replayed',roles:['renewable_planner','operations_reviewer'],requiresEvidence:true},
    {from:'scenario_replayed',action:'record_dispatch_proposal',to:'dispatch_proposed',roles:['renewable_planner'],requiresEvidence:true},
    {from:'dispatch_proposed',action:'submit_operator_review',to:'operator_review',roles:['operations_reviewer','safety_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'operator_review',action:'approve_observed_dispatch',to:'dispatch_approved',roles:['operations_manager','safety_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'dispatch_approved',action:'record_execution',to:'execution_observed',roles:['integration_operator','operations_manager'],requiresEvidence:true},
    {from:'dispatch_approved',action:'record_failure',to:'execution_failed',roles:['integration_operator','operations_manager'],requiresEvidence:true},
    {from:'dispatch_approved',action:'record_offline_pending',to:'offline_pending',roles:['integration_operator'],requiresEvidence:true},
    {from:'execution_failed',action:'verify_manual_fallback',to:'manual_fallback_verified',roles:['safety_reviewer','operations_manager'],requiresEvidence:true,dualControl:true},
    {from:'offline_pending',action:'verify_manual_fallback',to:'manual_fallback_verified',roles:['safety_reviewer','operations_manager'],requiresEvidence:true,dualControl:true},
    {from:'execution_observed',action:'reconcile_outcome',to:'outcome_reconciled',roles:['operations_reviewer','operations_manager'],requiresEvidence:true,dualControl:true},
    {from:'manual_fallback_verified',action:'reconcile_outcome',to:'outcome_reconciled',roles:['operations_reviewer','operations_manager'],requiresEvidence:true,dualControl:true},
    {from:'outcome_reconciled',action:'close_plan',to:'closed',roles:['operations_manager','auditor'],requiresEvidence:true}
  ],
  acceptedFixture:{telemetryVersion:'t1',scadaVersion:'s1',assetVersion:'a1',gisVersion:'g1',constraintVersion:'c1',modelVersion:'m1',policyVersion:'p1',safetyLimitsVerified:true,sourceFreshnessSeconds:20,forecastError:0.07,constraintViolations:0,p95LatencyMs:700,missedEventRate:0.01,realizedOutputRatio:0.94,offlineStatus:'reconciled'},
  rejectedFixture:{telemetryVersion:'t1',scadaVersion:'s1',assetVersion:'a1',gisVersion:'g1',constraintVersion:'c1',modelVersion:'m1',policyVersion:'p1',safetyLimitsVerified:true,sourceFreshnessSeconds:20,forecastError:0.07,constraintViolations:1,p95LatencyMs:700,missedEventRate:0.01,realizedOutputRatio:0.94,offlineStatus:'reconciled'},
  readyDisposition:'independent_renewable_operator_review_required',holdDisposition:'forecast_constraint_latency_or_offline_hold',decisionField:'scadaDispatchCommand',
  assess:x=>{const freshness=Number(x.sourceFreshnessSeconds),error=Number(x.forecastError),violations=Number(x.constraintViolations),latency=Number(x.p95LatencyMs),missed=Number(x.missedEventRate),output=Number(x.realizedOutputRatio);const ready=x.safetyLimitsVerified===true&&freshness<=120&&error<=0.12&&violations===0&&latency<=1000&&missed<=0.02&&output>=0.85&&x.offlineStatus==='reconciled';return{disposition:ready?'independent_renewable_operator_review_required':'forecast_constraint_latency_or_offline_hold',scadaDispatchCommand:null,gridBidCommand:null,fieldDispatchCommand:null,metrics:{freshness,error,violations,latency,missed,output},versions:{telemetry:x.telemetryVersion,scada:x.scadaVersion,assets:x.assetVersion,gis:x.gisVersion,constraints:x.constraintVersion,model:x.modelVersion}};}
};
